- name: Create repository
  command: "kopia repository create google --bucket {{ kopia_gcs_bucket }} --password '{{ kopia_gcs_password }}'"
  args:
    creates: "~/.config/kopia/repository.config"

- name: Handle repo connection
  block:
    - name: Check if repo is connected
      command: kopia repository status
      changed_when: false
  rescue:
    - name: Connect to repository
      command: "kopia repository connect google --bucket {{ kopia_gcs_bucket }} --password '{{ kopia_gcs_password }}'"
