- name: Adds deb repository
  apt_key:
    url: https://kopia.io/signing-key

- name: Adds apt source
  apt_repository:
    repo: "deb http://packages.kopia.io/apt/ stable main"

- name: Install kopia & fuse
  apt:
    pkg:
      - fuse
      - kopia
    state: present

- name: Add environment variables
  lineinfile:
    path: /etc/environment
    line: "{{ item.key | upper }}={{ item.value }}"
    create: yes
  with_dict: "{{ kopia_environment_vars }}"

- name: Add /var/log/kopia directory for cron logs
  file:
    path: /var/log/kopia
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Add logrotate entry for logs
  template:
    src: kopia.logrotate.j2
    dest: /etc/logrotate.d/kopia
    owner: root
    group: root
    mode: 0644
