---
- import_tasks: install.yml
  tags:
    - kopia
    - kopia:install

- import_tasks: gcs.yml
  when: kopia_gcs_bucket is defined
  tags:
    - kopia
    - kopia:gcs


- import_tasks: gdrive.yml
  when: kopia_gdrive_folder_id is defined
  tags:
    - kopia
    - kopia:gdrive
